version: "3"

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile

  proxy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    depends_on:
      - server
    ports:
      - "8080:8080"

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "8081:8081"