version: "3"

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "9090:9090"

  proxy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    depends_on:
      - server
    ports:
      - "8080:8080"